"""Finished Passenger module

Revision ID: 05eae7637134
Revises: bed594a4138a
Create Date: 2023-07-15 15:37:33.164087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05eae7637134'
down_revision = 'bed594a4138a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
