"""cleaned up code in models.py

Revision ID: 0b369b3322fc
Revises: 25d3900f9cd1
Create Date: 2023-07-12 11:43:14.670214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b369b3322fc'
down_revision = '25d3900f9cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
