"""updated cli.py to look up flight information from airlines

Revision ID: 0d86e9257a04
Revises: f106c5b1d120
Create Date: 2023-07-14 13:17:56.197988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d86e9257a04'
down_revision = 'f106c5b1d120'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
