"""Completed seed.py file

Revision ID: 19feb03ca7e8
Revises: ceac0fa6e035
Create Date: 2023-07-13 15:23:20.563390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19feb03ca7e8'
down_revision = 'ceac0fa6e035'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
