"""updated cli.py with main() function

Revision ID: 25d3900f9cd1
Revises: 28cdef872c8f
Create Date: 2023-07-12 11:29:03.435672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d3900f9cd1'
down_revision = '28cdef872c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
