"""added airline to Flight class

Revision ID: 28cdef872c8f
Revises: b45bb12b88df
Create Date: 2023-07-11 13:09:40.911574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cdef872c8f'
down_revision = 'b45bb12b88df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('airline', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'airline')
    # ### end Alembic commands ###
