"""Changed flight_choice 1 to 2 and added flight_choice 1 and 3

Revision ID: 34be8ceca788
Revises: 0d86e9257a04
Create Date: 2023-07-15 13:04:16.136008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34be8ceca788'
down_revision = '0d86e9257a04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
