"""Initial migration

Revision ID: 354eb27467f2
Revises: 
Create Date: 2023-07-16 12:33:31.800892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354eb27467f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'reservations', 'passengers', ['passenger_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    # ### end Alembic commands ###
