"""Fixed issue with looping through classes_list in seed.py

Revision ID: 3f5c1d5767ae
Revises: af04dce4cbf8
Create Date: 2023-07-13 15:51:09.583548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5c1d5767ae'
down_revision = 'af04dce4cbf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
