"""Created backref for Reservations to Passengers table

Revision ID: 4bd3a5a1f383
Revises: 2e94bb627897
Create Date: 2023-07-10 15:51:58.491681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd3a5a1f383'
down_revision = '2e94bb627897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
