"""updated format for departure and arrival time in seeds.py and changed each from integer to string in models.py to get appropriate time format

Revision ID: 7674596163dc
Revises: 92d1c69093cd
Create Date: 2023-07-13 13:09:58.160190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7674596163dc'
down_revision = '92d1c69093cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
