"""Updated functions in revervation_functions.py to include corresponding passenger information

Revision ID: 8579492afdb1
Revises: f4ded78a4ffa
Create Date: 2023-07-17 08:49:08.029043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8579492afdb1'
down_revision = 'f4ded78a4ffa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
