"""Created helpers folder and added flight_info_functions.py

Revision ID: 8783867628a2
Revises: 34be8ceca788
Create Date: 2023-07-15 13:39:10.488797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8783867628a2'
down_revision = '34be8ceca788'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
