"""Fixed seed.py file so that departure_time and arrival_time take a random integer and not a datetime

Revision ID: 92d1c69093cd
Revises: 9fb8fff93ef8
Create Date: 2023-07-13 12:27:47.519976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d1c69093cd'
down_revision = '9fb8fff93ef8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
