"""changed relationship from passenger and reservation to flight and reservation

Revision ID: 9abedc0f8467
Revises: affbf50b1786
Create Date: 2023-07-12 13:00:54.939705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abedc0f8467'
down_revision = 'affbf50b1786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passengers', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('passengers', sa.Column('last_name', sa.String(), nullable=True))
    op.drop_column('passengers', 'name')
    op.add_column('reservations', sa.Column('flight_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'flights', ['flight_id'], ['id'])
    op.drop_column('reservations', 'passenger_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('passenger_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'passengers', ['passenger_id'], ['id'])
    op.drop_column('reservations', 'flight_id')
    op.add_column('passengers', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('passengers', 'last_name')
    op.drop_column('passengers', 'first_name')
    # ### end Alembic commands ###
