"""Completed seed.py file

Revision ID: af04dce4cbf8
Revises: 19feb03ca7e8
Create Date: 2023-07-13 15:24:48.539004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af04dce4cbf8'
down_revision = '19feb03ca7e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
