"""updating seed.py and installing faker

Revision ID: affbf50b1786
Revises: 0b369b3322fc
Create Date: 2023-07-12 12:11:21.387870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'affbf50b1786'
down_revision = '0b369b3322fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
