"""Updated seed.py to include reservation instances

Revision ID: b43db6575628
Revises: d4f2fa667640
Create Date: 2023-07-13 14:57:48.970176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43db6575628'
down_revision = 'd4f2fa667640'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('class_type', sa.String(), nullable=True))
    op.drop_column('reservations', 'class_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('class_list', sa.VARCHAR(), nullable=True))
    op.drop_column('reservations', 'class_type')
    # ### end Alembic commands ###
