"""updating debug.py

Revision ID: b45bb12b88df
Revises: 4bd3a5a1f383
Create Date: 2023-07-11 12:31:25.214960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45bb12b88df'
down_revision = '4bd3a5a1f383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
