"""updating seed.py for random flight info

Revision ID: bd68f6d826d8
Revises: affbf50b1786
Create Date: 2023-07-12 14:06:21.017222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd68f6d826d8'
down_revision = 'affbf50b1786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'flights', ['flight_id'], ['id'])
    op.drop_column('reservations', 'passenger_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('passenger_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'passengers', ['passenger_id'], ['id'])
    # ### end Alembic commands ###
