"""updating seed.py for random flight info

Revision ID: bd68f6d826d8
Revises: affbf50b1786
Create Date: 2023-07-12 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite


# revision identifiers, used by Alembic.
revision = 'bd68f6d826d8'
down_revision = 'affbf50b1786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE TABLE new_reservations (id INTEGER PRIMARY KEY AUTOINCREMENT, flight_id INTEGER)')
    op.execute('INSERT INTO new_reservations (id, flight_id) SELECT id, flight_id FROM reservations')
    op.drop_table('reservations')
    op.rename_table('new_reservations', 'reservations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE TABLE new_reservations (id INTEGER PRIMARY KEY AUTOINCREMENT, flight_id INTEGER)')
    op.execute('INSERT INTO new_reservations (id, flight_id) SELECT id, flight_id FROM reservations')
    op.drop_table('reservations')
    op.rename_table('new_reservations', 'reservations')
    # ### end Alembic commands ###