"""Changed economy class to coach in seed.py

Revision ID: c000fbdfd58c
Revises: 3f5c1d5767ae
Create Date: 2023-07-14 11:02:02.227173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c000fbdfd58c'
down_revision = '3f5c1d5767ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
