"""Updated seed.py to include reservation instances

Revision ID: ceac0fa6e035
Revises: b43db6575628
Create Date: 2023-07-13 15:20:40.174566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceac0fa6e035'
down_revision = 'b43db6575628'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('flight_class', sa.String(), nullable=True))
    op.drop_column('reservations', 'class_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('class_type', sa.VARCHAR(), nullable=True))
    op.drop_column('reservations', 'flight_class')
    # ### end Alembic commands ###
