"""added class_list to Reservations class in models.py

Revision ID: d0e03fef5882
Revises: 7674596163dc
Create Date: 2023-07-13 13:22:47.045996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e03fef5882'
down_revision = '7674596163dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('class_list', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'class_list')
    # ### end Alembic commands ###
