"""Updated seed.py to include passenger instances

Revision ID: d4f2fa667640
Revises: d0e03fef5882
Create Date: 2023-07-13 14:00:44.609548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f2fa667640'
down_revision = 'd0e03fef5882'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
