"""Testing migrations

Revision ID: de0a906f7bcc
Revises: 354eb27467f2
Create Date: 2023-07-16 12:37:55.591032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0a906f7bcc'
down_revision = '354eb27467f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'reservations', 'passengers', ['passenger_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    # ### end Alembic commands ###
