"""Updated cli.py file

Revision ID: f106c5b1d120
Revises: c000fbdfd58c
Create Date: 2023-07-14 11:49:45.879150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f106c5b1d120'
down_revision = 'c000fbdfd58c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
