"""Updated def view_all_reservations in reservation_functions.py to include the relationship between passenger and reservations

Revision ID: f4ded78a4ffa
Revises: 5857082dce2f
Create Date: 2023-07-17 08:23:56.838667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ded78a4ffa'
down_revision = '5857082dce2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
